"""
Authentik deployment automation tasks
"""
import os
import secrets
import string
from invoke import task

# Environment variables
VPS_HOST = os.environ.get("VPS_HOST")
INTERNAL_DOMAIN = os.environ.get("INTERNAL_DOMAIN")

def generate_secret(length=50):
    alphabet = string.ascii_letters + string.digits
    return ''.join(secrets.choice(alphabet) for i in range(length))

@task
def prepare(c):
    """Prepare Authentik data directories"""
    print("\n📁 Preparing Authentik data directories...")
    dirs = [
        "/data/platform/authentik/postgres",
        "/data/platform/authentik/redis",
        "/data/platform/authentik/media",
        "/data/platform/authentik/certs"
    ]
    for d in dirs:
        c.run(f"ssh root@{VPS_HOST} 'mkdir -p {d}'")
    
    # Set permissions (Authentik usually runs as 1000 or root, let's ensure 1000)
    c.run(f"ssh root@{VPS_HOST} 'chown -R 1000:1000 /data/platform/authentik'")
    c.run(f"ssh root@{VPS_HOST} 'chmod -R 755 /data/platform/authentik'")
    print("✅ Directories ready")

@task
def generate_env(c):
    """Generate local .env variables for Authentik (one-time)"""
    print("\n🔐 Generating Authentik secrets...")
    
    # Generate secrets if not already in .env
    pg_pass = generate_secret(24)
    authentik_key = generate_secret(50)
    
    print("\n" + "="*60)
    print("📋 PLEASE ADD THESE TO YOUR DOKPLOY ENVIRONMENT VARIABLES:")
    print("="*60)
    print(f"PG_PASS: {pg_pass}")
    print(f"AUTHENTIK_SECRET_KEY: {authentik_key}")
    print("="*60)
    print("\nNote: These should also be saved in Vault/1Password for future reference.")

@task(pre=[prepare])
def deploy(c):
    """Deploy Authentik to Dokploy (Manual steps)"""
    print("\n🚀 Deploying Authentik...")
    print("\n" + "="*60)
    print("⏸️  Please complete the following in Dokploy UI:")
    print("="*60)
    print(f"1. Access: https://cloud.{INTERNAL_DOMAIN}")
    print("2. Create Project: bootstrap (if not exists)")
    print("3. Create Docker Compose App:")
    print("   - Name: authentik")
    print("   - Repository: GitHub → wangzitian0/infra2")
    print("   - Branch: main (or your feature branch)")
    print("   - Compose Path: platform/01.authentik/compose.yaml")
    print("4. Add Environment Variables in Dokploy:")
    print("   - PG_PASS (generated by 'invoke authentik.generate-env')")
    print("   - AUTHENTIK_SECRET_KEY (generated by 'invoke authentik.generate-env')")
    print("5. Click Deploy")
    print("="*60)
    
    input("\n✋ Press Enter to continue after deployment completion...")

@task
def status(c):
    """Check Authentik status"""
    print(f"\n🔍 Checking Authentik status...")
    c.run(f"curl -s -I https://auth.{INTERNAL_DOMAIN}", warn=True)
    c.run(f"ssh root@{VPS_HOST} 'docker ps | grep authentik'", warn=True)

@task(pre=[prepare, generate_env, deploy])
def setup(c):
    """Complete Authentik setup flow"""
    print("\n✅ Authentik setup complete!")
    print(f"Initial Setup URL: https://auth.{INTERNAL_DOMAIN}/if/flow/initial-setup/")
    print("\nImportant: The first user to access this URL will be the superuser.")
