"""Drift audit for finance_report's required-env manifest vs secrets.ctmpl (#482)."""
from __future__ import annotations

import json
from pathlib import Path

import pytest
import yaml

from tools.validate_required_env import MANIFEST, ManifestShapeError, TEMPLATE, audit, main

ROOT = Path(__file__).resolve().parents[2]
WORKFLOW = ROOT / ".github" / "workflows" / "infra-ci.yml"

# infra-ci deliberately never checks out submodules by default (#506) — only the
# dedicated validate-required-env CI job does a scoped `git submodule update --init
# repos/finance_report`. The general `libs/tests` run (every other CI job, and a plain
# local checkout before running `invoke setup`) has no submodule content, so the two
# "real" tests below must skip rather than fail when the manifest isn't there.
_SUBMODULE_CHECKED_OUT = (ROOT / MANIFEST).exists()
_SKIP_REASON = "repos/finance_report submodule not checked out"


def _write(root: Path, fields: list[dict], template_lines: list[str]) -> None:
    manifest_path = root / MANIFEST
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps({"fields": fields}), encoding="utf-8")

    template_path = root / TEMPLATE
    template_path.parent.mkdir(parents=True, exist_ok=True)
    template_path.write_text("\n".join(template_lines) + "\n", encoding="utf-8")


def _field(env: str, *, vault: bool, aliases: list[str] | None = None) -> dict:
    return {"field": env.lower(), "env": env, "aliases": aliases or [], "group": "Test", "vault": vault, "has_default": True}


@pytest.mark.skipif(not _SUBMODULE_CHECKED_OUT, reason=_SKIP_REASON)
def test_real_manifest_and_template_are_in_sync() -> None:
    result = audit()
    assert result["unbacked_vault_fields"] == []
    assert result["stale_template_entries"] == []


@pytest.mark.skipif(not _SUBMODULE_CHECKED_OUT, reason=_SKIP_REASON)
def test_real_enforce_exits_zero() -> None:
    assert main(["--enforce"]) == 0


def test_unbacked_vault_field_is_flagged(tmp_path: Path) -> None:
    _write(
        tmp_path,
        fields=[_field("SECRET_KEY", vault=True)],
        template_lines=['DEBUG={{ with .Data.data.DEBUG }}{{ printf "%q" . }}{{ else }}"false"{{ end }}'],
    )
    result = audit(tmp_path)
    assert result["unbacked_vault_fields"] == ["SECRET_KEY"]
    assert result["stale_template_entries"] == ["DEBUG"]


def test_alias_satisfies_the_vault_requirement(tmp_path: Path) -> None:
    _write(
        tmp_path,
        fields=[_field("ZAI_API_KEY", vault=True, aliases=["AI_API_KEY", "GEMINI_API_KEY"])],
        template_lines=['AI_API_KEY={{ with .Data.data.AI_API_KEY }}{{ printf "%q" . }}{{ else }}""{{ end }}'],
    )
    result = audit(tmp_path)
    assert result["unbacked_vault_fields"] == []
    assert result["stale_template_entries"] == []


def test_non_vault_field_with_no_render_is_not_flagged(tmp_path: Path) -> None:
    _write(
        tmp_path,
        fields=[_field("ACCESS_TOKEN_EXPIRE_MINUTES", vault=False)],
        template_lines=['SECRET_KEY={{ with .Data.data.SECRET_KEY }}{{ printf "%q" . }}{{ else }}""{{ end }}'],
    )
    result = audit(tmp_path)
    assert result["unbacked_vault_fields"] == []
    assert result["stale_template_entries"] == ["SECRET_KEY"]


def test_enforce_fails_closed_on_drift() -> None:
    class _StubArgs:
        enforce = True

    # exercise main()'s drift branch directly against a synthetic root via monkeypatched audit
    import tools.validate_required_env as mod

    original_audit = mod.audit
    try:
        mod.audit = lambda root=ROOT: {"unbacked_vault_fields": ["X"], "stale_template_entries": []}
        assert main(["--enforce"]) == 1
        assert main([]) == 0
    finally:
        mod.audit = original_audit


# --- #523: defensive manifest-schema handling -------------------------------------
#
# required-env.generated.json is generated by finance_report, a foreign repo infra2
# doesn't control the shape of. Any of the shapes below must degrade this gate to a
# clear, non-fatal report (audit() raises ManifestShapeError, main() catches it and
# exits 0) rather than crashing with a raw traceback or silently producing an empty
# manifest that reads as mass "drift" (see #523 root cause).


def _write_raw_manifest(root: Path, content: str) -> None:
    manifest_path = root / MANIFEST
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(content, encoding="utf-8")


def test_non_json_manifest_raises_shape_error(tmp_path: Path) -> None:
    _write_raw_manifest(tmp_path, "{this is not json")
    with pytest.raises(ManifestShapeError):
        audit(tmp_path)


def test_manifest_missing_fields_key_raises_shape_error(tmp_path: Path) -> None:
    _write_raw_manifest(tmp_path, json.dumps({"generated_by": "finance_report", "source": "Settings"}))
    with pytest.raises(ManifestShapeError):
        audit(tmp_path)


def test_manifest_fields_not_a_list_raises_shape_error(tmp_path: Path) -> None:
    _write_raw_manifest(tmp_path, json.dumps({"fields": {"SECRET_KEY": {"vault": True}}}))
    with pytest.raises(ManifestShapeError):
        audit(tmp_path)


def test_manifest_field_missing_expected_key_raises_shape_error(tmp_path: Path) -> None:
    # missing "aliases"
    _write_raw_manifest(tmp_path, json.dumps({"fields": [{"env": "SECRET_KEY", "vault": True}]}))
    with pytest.raises(ManifestShapeError):
        audit(tmp_path)


def test_manifest_field_aliases_null_raises_shape_error(tmp_path: Path) -> None:
    _write_raw_manifest(
        tmp_path, json.dumps({"fields": [{"env": "SECRET_KEY", "aliases": None, "vault": True}]})
    )
    with pytest.raises(ManifestShapeError):
        audit(tmp_path)


def test_manifest_field_aliases_non_list_raises_shape_error(tmp_path: Path) -> None:
    _write_raw_manifest(
        tmp_path, json.dumps({"fields": [{"env": "SECRET_KEY", "aliases": "AI_API_KEY", "vault": True}]})
    )
    with pytest.raises(ManifestShapeError):
        audit(tmp_path)


def test_manifest_field_vault_non_bool_raises_shape_error(tmp_path: Path) -> None:
    _write_raw_manifest(
        tmp_path, json.dumps({"fields": [{"env": "SECRET_KEY", "aliases": [], "vault": "true"}]})
    )
    with pytest.raises(ManifestShapeError):
        audit(tmp_path)


def test_main_degrades_to_exit_zero_on_manifest_shape_error() -> None:
    # main() must not crash and must not fail-closed (even under --enforce) when the
    # manifest itself is unreadable/malformed — that's a schema problem to report, not
    # genuine drift to fail the build over.
    import tools.validate_required_env as mod

    original_audit = mod.audit
    try:
        def _raise(root=ROOT):
            raise ManifestShapeError("synthetic shape mismatch for test")

        mod.audit = _raise
        assert main([]) == 0
        assert main(["--enforce"]) == 0
    finally:
        mod.audit = original_audit


def test_infra_ci_paths_filter_covers_finance_report_submodule() -> None:
    # #523: a pure submodule-pin-bump PR touches only repos/finance_report (the
    # submodule gitlink), not finance_report/** (infra2's own deploy config dir). Both
    # the pull_request and push triggers must list the submodule path so the PR that
    # bumps the pin is the one that catches its own manifest drift.
    workflow = yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))
    on_triggers = workflow[True]  # PyYAML (YAML 1.1) parses the bare `on:` key as bool True
    pr_paths = on_triggers["pull_request"]["paths"]
    push_paths = on_triggers["push"]["paths"]
    assert "repos/finance_report/**" in pr_paths
    assert "repos/finance_report/**" in push_paths
