"""Backward-compatibility shim — the implementation lives in
`libs.observability.issue_trail`.

Re-exports only. See `libs/README.md` § Backward-Compatibility Shims: never add new
business logic here; it belongs in the domain package this module points at.
"""

from __future__ import annotations

from libs.observability.issue_trail import (
    API_BASE,
    API_TIMEOUT_SECONDS,
    DRY_RUN_ENV,
    EXPECTED_SOURCES,
    FULL,
    ISSUE_LABELS,
    MAX_DETAIL_CHARS,
    MAX_PAGES,
    OFF,
    OPEN_ONLY,
    PER_PAGE,
    RUNNER_HEALTH_SOURCE,
    SSH_OVERRIDE_ENV,
    TITLE_PREFIX,
    VERDICTS_ENV,
    WATCHDOG_SOURCE,
    CheckVerdict,
    GitHubIssueClient,
    GitHubIssues,
    IssueApi,
    ListingFailed,
    Trail,
    WriteFailed,
    check_name,
    issue_trail_mode,
    load_trail,
    reconcile,
    reconcile_watchdog_issues,
    record_verdicts,
    scrub,
    title_for,
)

__all__ = [
    "API_BASE",
    "API_TIMEOUT_SECONDS",
    "DRY_RUN_ENV",
    "EXPECTED_SOURCES",
    "FULL",
    "GitHubIssueClient",
    "GitHubIssues",
    "ISSUE_LABELS",
    "IssueApi",
    "ListingFailed",
    "MAX_DETAIL_CHARS",
    "MAX_PAGES",
    "OFF",
    "OPEN_ONLY",
    "PER_PAGE",
    "RUNNER_HEALTH_SOURCE",
    "SSH_OVERRIDE_ENV",
    "TITLE_PREFIX",
    "Trail",
    "VERDICTS_ENV",
    "WATCHDOG_SOURCE",
    "CheckVerdict",
    "WriteFailed",
    "check_name",
    "issue_trail_mode",
    "load_trail",
    "reconcile",
    "reconcile_watchdog_issues",
    "record_verdicts",
    "scrub",
    "title_for",
]
